steps:
  - label: "Compute what to trigger"
    command: |
      echo "figured out what to trigger"
      echo "example-1" >> trigger_this

  - label: "Trigger example-1"
    command: |
      cat 1.yaml | buildkite-agent pipeline upload
